### ISSUE TITLE
Caravele doesn't provide internal picorv32 interrupts!

### ISSUE THREAD

**Issue by jean-m-cyr** [efabless/caravel_mpw-one#11]
The Caravel SOC design has one external interrupt pin, but doesn't seem to provide any accessible internal interrupt ports for internal wishbone slave peripheral user projects that would need them. It would be a shame to have to drive an extra output pin just to loop it back to the external interrupt input pin.

**Comment by RTimothyEdwards** [comment]
You're wanting to have the user project be able to raise an interrupt on the managment SoC through the wishbone bus?

**Comment by ohAitch** [comment]
I believe that is the feature request seen on slack, correct.

**Comment by jean-m-cyr** [comment]
Not over the bus. Wishbone doesn't support it. More likely one or two unused wires into the interrupt controller. Something akin to the user_clock2 signal user project port.

**Comment by RTimothyEdwards** [comment]
This issue was corrected on the caravel version for MPW-two, so I am closing this issue now.
