### ISSUE TITLE
[CI] periodically print progress information during DRC check

### ISSUE THREAD

**Issue by ohAitch** [efabless/caravel_mpw-one#16]
So Travis CI doesn't time out the build after 10 minutes.

Efabless hosted precheck runs 20 minutes, so adding a dummy `(sleep; echo)&` to fire at minute 7 and minute 14 should be more than sufficient. If it is straightforward to add a `open_mpw_precheck` flag that shows >0 but <100 lines of precheck output as they come in that would ofc be preferable.

**Comment by agorararmard** [comment]
@ohAitch: I was waiting for the travis support to extend the overall timeout before applying the log timeout extension changes. I guess the cleanest way for that would be to use `travis wait`.
