### ISSUE TITLE
Move the documentation from PS/PDF format to RST

### ISSUE THREAD

**Issue by glatosinski** [efabless/caravel_mpw-one#26]
## Expected behaviour

The source code for the documentation should be available in the repository, along with the generation of the documentation in HTML and PDF formats.

## Current behaviour

The documentation is currently available under `doc/caravel_datasheet.pdf`.

This issue covers initial work on creating readthedocs pipeline and rewriting the current documentation from `doc/caravel_datasheet.pdf` to the RST files for Sphinx documentation.

**Comment by agorararmard** [comment]
With #25 merged, this issue is resolved. Thank you very much for the PR and the effort!

Here is the documentation from develop: https://caravel-harness.readthedocs.io/en/develop/ I'll cleanup some files and merge that to master soon.

Thank you very much, again!
