### ISSUE TITLE
No link to the documentation at https://caravel-docs.readthedocs.io/en/moving-to-rst/index.html

### ISSUE THREAD

**Issue by mithro** [efabless/caravel_mpw-one#38]
There doesn't seem to be any links in this repository to the awesome documentation at https://caravel-docs.readthedocs.io/en/moving-to-rst/index.html

**Comment by agorararmard** [comment]
@mithro: It was added to master! https://caravel-harness.readthedocs.io/en/latest/ 
The link is in the README.rst right under the caravel picture.

**Comment by mithro** [comment]
Maybe you could add it as the URL for this repository?

**Comment by agorararmard** [comment]
@mithro: That makes sense. I added it, and I'll do the same for openlane!
I'm closing this issue.
